# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='media/facebook.jpg', upload_to='profile_pics'),
        ),
    ]
